import { connectToDatabase } from "../src/db";
import { PostAnalysis } from "../src/models/PostAnalysis";
import { Post } from "../src/models/Post";
import mongoose from "mongoose";
import Redis from "ioredis";
import { createRedisConnectionOptions } from "../src/queues/redis";

const API_BASE_URL = "http://localhost:3001";

async function run() {
  console.log("--- Starting Gemini Integration Test ---");

  // 1. Connect to Redis and delete the target keys to reset BullMQ job status
  console.log("Connecting to Redis...");
  const redisOptions = createRedisConnectionOptions();
  const redis = new Redis(redisOptions);
  
  const deletedKeys = await redis.del(
    "bull:analysis:mock-post-1",
    "bull:embedding:mock-post-1",
    "bull:user-intelligence:gemini_test_user",
    "bull:lead-qualification:gemini_test_user"
  );
  console.log(`✓ Deleted ${deletedKeys} job keys from Redis.`);
  redis.disconnect();

  // 2. Connect to MongoDB and clear documents for gemini_test_user
  await connectToDatabase();
  const deletedAnalyses = await PostAnalysis.deleteMany({ username: "gemini_test_user" });
  const deletedPosts = await Post.deleteMany({ username: "gemini_test_user" });
  console.log(`✓ Cleared ${deletedAnalyses.deletedCount} old analysis records and ${deletedPosts.deletedCount} old post records.`);

  // 3. Trigger scenario
  const username = "gemini_test_user";
  const scenario = "success";
  console.log(`Triggering scenario '${scenario}' for @${username}...`);

  const triggerRes = await fetch(`${API_BASE_URL}/dev/trigger-scenario`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ scenario, username })
  });

  if (!triggerRes.ok) {
    throw new Error(`Trigger scenario failed: ${triggerRes.status} ${triggerRes.statusText}`);
  }

  const triggerData = await triggerRes.json() as any;
  console.log("Trigger response:", triggerData);

  // 4. Poll MongoDB for the post analysis result
  console.log("Polling MongoDB for PostAnalysis result...");
  let found = false;
  for (let i = 0; i < 30; i++) {
    const analysis = await PostAnalysis.findOne({ username });
    if (analysis) {
      console.log("✓ Success! Found AI Analysis generated by Gemini:");
      console.log(JSON.stringify(analysis.toJSON(), null, 2));
      found = true;
      break;
    }
    await new Promise(r => setTimeout(r, 1000));
  }

  if (!found) {
    console.error("❌ Failed to find Gemini analysis record after 30 seconds.");
  }

  await mongoose.connection.close();
  console.log("--- Gemini Integration Test Complete ---");
}

run().catch(err => {
  console.error("Test execution failed:", err);
  process.exit(1);
});
